// PG-EOS · scribe.mjs — generates docs/PROJECT_STATE.md (ADR-0005 §5–§6, CLAUDE.md · DOCUMENTS).
//
// Sources (hand-maintained, short): docs/state/header.md, docs/state/blockers.md, docs/state/next.md,
// the lock table in tasks/LANE_LOCKS.md, and `git log` for the last five feat/fix(<WBS>) commits.
//   --write   regenerate docs/PROJECT_STATE.md
//   --check   exit 1 if PROJECT_STATE.md differs from the generated text, exceeds the limits, or a
//             source line is over LINE_MAX / carries the `<this commit>` placeholder
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
const OUT = 'docs/PROJECT_STATE.md';
const LINE_MAX = 160;
const LINES_MAX = 40;
const DONE_COUNT = 5;
const PLACEHOLDER = '<this commit>';
const SOURCE_LIMITS = { 'docs/state/header.md': 8, 'docs/state/blockers.md': 12, 'docs/state/next.md': 3 };

function read(rel) {
  return readFileSync(join(ROOT, rel), 'utf8');
}

function sourceLines(rel) {
  const lines = read(rel).split('\n').filter((l) => l.trim() !== '');
  const max = SOURCE_LIMITS[rel];
  if (lines.length > max) throw new Error(`${rel}: ${lines.length} lines, limit ${max}`);
  for (const [i, l] of lines.entries()) {
    if (l.length > LINE_MAX) throw new Error(`${rel}:${i + 1}: ${l.length} chars, limit ${LINE_MAX}`);
    if (l.includes(PLACEHOLDER)) throw new Error(`${rel}:${i + 1}: unresolved ${PLACEHOLDER}`);
  }
  return lines;
}

function laneRows() {
  const rows = [];
  for (const line of read('tasks/LANE_LOCKS.md').split('\n')) {
    const m = /^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/.exec(line);
    if (!m || m[1] === 'module' || /^-+$/.test(m[1])) continue;
    rows.push(`- lane ${m[2]} · ${m[1]} · ${m[3]} · since ${m[4]}`);
  }
  return rows.length > 0 ? rows : ['- (no lock held)'];
}

function lastDone() {
  const log = execFileSync('git', ['log', '--format=%h%x09%s', '-n', '80'], { cwd: ROOT, encoding: 'utf8' });
  const rows = [];
  for (const line of log.split('\n')) {
    const [hash, subject] = line.split('\t');
    if (!subject || !/^(feat|fix)\([^)]+\): /.test(subject)) continue;
    rows.push(`- \`${hash}\` ${subject.slice(0, LINE_MAX - 12)}`);
    if (rows.length === DONE_COUNT) break;
  }
  return rows;
}

function render() {
  const out = [
    '# PROJECT_STATE — PG-EOS (generated by scripts/scribe.mjs — edit docs/state/*.md and tasks/LANE_LOCKS.md, never this file)',
    '',
    ...sourceLines('docs/state/header.md'),
    '',
    '## Lanes (tasks/LANE_LOCKS.md)',
    ...laneRows(),
    '',
    `## Last ${DONE_COUNT} feat/fix commits (git log)`,
    ...lastDone(),
    '',
    '## Blockers',
    ...sourceLines('docs/state/blockers.md').map((l) => `- ${l}`),
    '',
    '## Next',
    ...sourceLines('docs/state/next.md').map((l, i) => `${i + 1}. ${l}`),
  ];
  if (out.length > LINES_MAX) throw new Error(`${OUT}: ${out.length} lines, limit ${LINES_MAX}`);
  return `${out.join('\n')}\n`;
}

const mode = process.argv[2];
if (mode !== '--write' && mode !== '--check') {
  process.stderr.write('usage: node scripts/scribe.mjs --write | --check\n');
  process.exit(2);
}

let text;
try {
  text = render();
} catch (error) {
  process.stderr.write(`scribe: ${error instanceof Error ? error.message : String(error)}\n`);
  process.exit(1);
}

if (mode === '--write') {
  writeFileSync(join(ROOT, OUT), text);
  process.stdout.write(`scribe: wrote ${OUT} (${text.split('\n').length - 1} lines)\n`);
} else if (read(OUT) !== text) {
  process.stderr.write(`scribe: ${OUT} is not the generated text — run: node scripts/scribe.mjs --write\n`);
  process.exit(1);
} else {
  process.stdout.write(`scribe: ${OUT} OK\n`);
}
