// modules/hr/infrastructure/calculate-daily-commission/repository.ts — WBS 3.13 part 2.
//
// infrastructure/ layer: every DB statement for the calculate-daily-commission use case, run
// against the `tx` a caller's own withIdempotentContext(ctx, idem, fn) already opened. Implements
// ../../application/calculate-daily-commission/ports.ts's `CommissionDailyRepository`.
//
// Cross-schema reads (imile.shipments_attributed, imile.driver_id_assignments) follow the
// `getContractCheck` pattern exactly (modules/wms/infrastructure/process-outbound/repository.ts:
// 245-280): plain SQL via `tx.execute`, no `modules/imile` TypeScript import (cross-module lint
// boundary) — same discipline the brief's own Read ONLY list cites.
//
// `insertCommissionDaily`'s own `id` is PRE-GENERATED by the application layer (deps.ids.next())
// and the INSERT never uses `RETURNING` — hr.commission_daily's own `own_commission` SELECT policy
// (migration 0027) is ALSO applied by Postgres to `INSERT ... RETURNING`, and this use case's own
// actor is not guaranteed to hold `hr.commission.read_all` or be the row's own employee (migration
// 0027's own header note). Every other column this insert needs (gross_commission, counts,
// version's own column default) is already known to the application layer before the INSERT runs,
// so no RETURNING clause is needed at all.

const COMMISSION_SCHEMA = 'hr'; // REPLACE-ON-COPY: the module schema.
const COMMISSION_DAILY_TABLE_NAME = 'commission_daily'; // REPLACE-ON-COPY: the aggregate table.
const COMMISSION_DAILY_TABLE = `${COMMISSION_SCHEMA}.${COMMISSION_DAILY_TABLE_NAME}`;
const COMMISSION_RULES_TABLE = `${COMMISSION_SCHEMA}.commission_rules`;
const EMPLOYEES_TABLE = `${COMMISSION_SCHEMA}.employees`; // hr.employees — round-1 finding 1's own read.
const AUDIT_ACTOR_TYPE_USER = 'user'; // every actor is ctx.userId — never 'system' here.

// database/schema/13-Schema-Additions.sql:349 `applies_to text not null default 'driver'` — this
// slice reads driver rules only (brief default 1).
const COMMISSION_RULES_APPLIES_TO_DRIVER = 'driver';

// live-verified constraint name (`select conname from pg_constraint where
// conrelid='hr.commission_daily'::regclass`), never a guessed Postgres auto-generated name — same
// discipline as assign-driver-id's own repository.ts.
const UNIQUE_VIOLATION_SQLSTATE = '23505';
const COMMISSION_DAILY_UNIQUE_CONSTRAINT = 'commission_daily_work_date_employee_id_key';

// imile.shipments.internal_status allowed values (.claude/briefs/imile.brief.md §3 /
// 13B-Schema-Reference-Consolidation.sql:2375-2376 chk_shipments_internal_status) — the three this
// use case counts.
const SHIPMENT_STATUS_DELIVERED = 'delivered';
const SHIPMENT_STATUS_FAILED = 'failed';
const SHIPMENT_STATUS_RETURNED = 'returned';

// part 2 round-2 finding 1 (timezone): doc 40 §A3 / 01-Data-Model.sql:8 — the platform's business
// timezone is Asia/Kuwait. All timestamps in this table are stored UTC (`timestamptz`), so a
// `workDate` calendar-day boundary must be pinned to Asia/Kuwait EXPLICITLY, never to whatever
// TimeZone the connecting session happens to carry (same mechanism as
// modules/wms/domain/take-occupancy-snapshot/invariants.ts's own `businessDateOf` — Asia/Kuwait
// carries a fixed UTC+3 offset year-round, no DST — here expressed as a literal SQL `AT TIME ZONE`
// cast instead of a domain-level Date shift, since this is a SQL comparison against timestamptz
// columns, not a Date already in hand). `timestamptz AT TIME ZONE zone` yields the local wall-clock
// `timestamp` in that zone (used to derive a calendar date); `date::timestamp AT TIME ZONE zone`
// does the reverse — interprets a naive midnight as Kuwait-local and yields the UTC instant.
const BUSINESS_TIMEZONE = 'Asia/Kuwait';

import { sql } from 'drizzle-orm';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';

import {
  CommissionAlreadyCalculatedError,
  EntityScopeAmbiguousError,
} from '../../domain/calculate-daily-commission/errors.js';
import type { CommissionRuleCandidate } from '../../domain/calculate-daily-commission/invariants.js';
import {
  COMMISSION_DAILY_STATUS_CALCULATED,
  type AttributedShipmentCounts,
  type CommissionDailyRepository,
  type InsertCommissionDailyColumns,
} from '../../application/calculate-daily-commission/ports.js';

/** True only for hr.commission_daily's `commission_daily_work_date_employee_id_key` unique
 *  violation. The whole `cause` chain is walked (drizzle wraps the failing query in its own error,
 *  carrying pg's DatabaseError — which holds the SQLSTATE and constraint name — as `cause`),
 *  bounded by `seen` against a cyclic chain. Same pattern as register-employee's
 *  `isDuplicateEmployeeCode` / assign-driver-id's own repository.ts. */
function isDuplicateCommissionDaily(error: unknown): boolean {
  const seen = new Set<unknown>();
  let current: unknown = error;

  while (current instanceof Error && !seen.has(current)) {
    seen.add(current);
    const code = 'code' in current ? current.code : undefined;
    const constraint = 'constraint' in current ? current.constraint : undefined;
    if (code === UNIQUE_VIOLATION_SQLSTATE && constraint === COMMISSION_DAILY_UNIQUE_CONSTRAINT) {
      return true;
    }
    current = current.cause;
  }

  return false;
}

/** brief, Contract: "entityId resolved from ctx" — resolved from identity.user_entities via
 *  platform.allowed_entities(), never trusted from the request body. Same discipline as
 *  register-employee/register-vehicle's own resolveCallerEntityId. Fails closed:
 *  cardinality(platform.allowed_entities()) = 1 -> use it; otherwise throw
 *  EntityScopeAmbiguousError (round-1 review finding 5 — was an untyped `Error`/500; replicates
 *  register-employee's own infrastructure/register-employee/repository.ts's typed-error shape)
 *  BEFORE any write — never guess by picking `[1]`. */
async function resolveCallerEntityId(tx: NodePgDatabase): Promise<string> {
  const result = await tx.execute<{ entity_id: string; entity_count: number }>(sql`
    select (platform.allowed_entities())[1] as entity_id, array_length(platform.allowed_entities(), 1) as entity_count
  `);
  const row = result.rows[0];
  const entityCount = row?.entity_count ?? 0;
  const entityId = row?.entity_id;
  if (entityCount !== 1 || !entityId) {
    throw new EntityScopeAmbiguousError(
      `platform.allowed_entities() returned ${entityCount} entities for the caller, not exactly ` +
        `one. (Allowed: a caller scoped to exactly one entity)`,
    );
  }
  return entityId;
}

/** round-1 review finding 1 (SECURITY/RLS): `employeeId`'s own `hr.employees.entity_id`, read
 *  through `hr.employees`' own `entity_scope` RLS policy — an employee row invisible to the
 *  caller (a different entity) returns no row, same as a non-existent id. `null` when no row is
 *  visible. Read BEFORE the shipments-attributed query and rule-matching (application layer's own
 *  step order) so an entity-A caller is refused before any entity-B data is even read. */
async function getEmployeeEntityId(tx: NodePgDatabase, employeeId: string): Promise<string | null> {
  const result = await tx.execute<{ entity_id: string }>(sql`
    select entity_id from ${sql.raw(EMPLOYEES_TABLE)} where id = ${employeeId}::uuid
  `);
  return result.rows[0]?.entity_id ?? null;
}

/** imile.shipments_attributed — the ONLY allowed view for attributing a shipment to a human driver
 *  (database/schema/13-Schema-Additions.sql:315-329 — "any direct join on driver_code is a
 *  critical review error"). Cross-schema, read-only, `getContractCheck` pattern: plain SQL via
 *  `tx.execute`, no `modules/imile` TypeScript import. */
async function getAttributedShipmentCounts(
  tx: NodePgDatabase,
  params: { readonly employeeId: string; readonly workDate: string },
): Promise<AttributedShipmentCounts> {
  const result = await tx.execute<{ internal_status: string; tracking_no: string }>(sql`
    select internal_status, tracking_no
      from imile.shipments_attributed
     where employee_id = ${params.employeeId}::uuid
       and (ofd_at AT TIME ZONE ${BUSINESS_TIMEZONE})::date = ${params.workDate}::date
  `);

  const deliveredTrackingNos: string[] = [];
  const failedTrackingNos: string[] = [];
  const returnedTrackingNos: string[] = [];

  for (const row of result.rows) {
    if (row.internal_status === SHIPMENT_STATUS_DELIVERED) deliveredTrackingNos.push(row.tracking_no);
    else if (row.internal_status === SHIPMENT_STATUS_FAILED) failedTrackingNos.push(row.tracking_no);
    else if (row.internal_status === SHIPMENT_STATUS_RETURNED) returnedTrackingNos.push(row.tracking_no);
  }

  return {
    deliveredCount: deliveredTrackingNos.length,
    failedCount: failedTrackingNos.length,
    returnedCount: returnedTrackingNos.length,
    deliveredTrackingNos,
    failedTrackingNos,
    returnedTrackingNos,
  };
}

/** the employee's ACTIVE imile.driver_id_assignments row covering the whole `workDate` calendar
 *  day (brief default 5) — `assigned_from` before the day ends AND (`assigned_to` null or after the
 *  day starts). `null` when none is active that day. Cross-schema, read-only, `getContractCheck`
 *  pattern. */
async function getActiveDriverIdRef(
  tx: NodePgDatabase,
  params: { readonly employeeId: string; readonly workDate: string },
): Promise<string | null> {
  // the Kuwait-local calendar day's own boundary, expressed as UTC timestamptz instants — never a
  // bare `::date` cast on a timestamptz column (this file's own `BUSINESS_TIMEZONE` header note).
  const result = await tx.execute<{ driver_id_ref: string }>(sql`
    select driver_id_ref
      from imile.driver_id_assignments
     where employee_id = ${params.employeeId}::uuid
       and assigned_from < ((${params.workDate}::date + 1)::timestamp AT TIME ZONE ${BUSINESS_TIMEZONE})
       and (assigned_to is null or assigned_to > (${params.workDate}::date::timestamp AT TIME ZONE ${BUSINESS_TIMEZONE}))
     order by assigned_from desc
     limit 1
  `);
  return result.rows[0]?.driver_id_ref ?? null;
}

/** candidate hr.commission_rules rows (brief default 1): entity_id, applies_to='driver',
 *  client_id is null, valid_from <= workDate, valid_to is null or valid_to >= workDate — the tier
 *  match itself is NOT done here, only in
 *  ../../domain/calculate-daily-commission/invariants.js's `selectCommissionRule`. */
async function getCandidateCommissionRules(
  tx: NodePgDatabase,
  params: { readonly entityId: string; readonly workDate: string },
): Promise<readonly CommissionRuleCandidate[]> {
  const result = await tx.execute<{
    id: string;
    tier_from: number;
    tier_to: number | null;
    rate_per_unit: string;
    min_daily: string | null;
  }>(sql`
    select id, tier_from, tier_to, rate_per_unit::text as rate_per_unit, min_daily::text as min_daily
      from ${sql.raw(COMMISSION_RULES_TABLE)}
     where entity_id = ${params.entityId}::uuid
       and applies_to = ${COMMISSION_RULES_APPLIES_TO_DRIVER}
       and client_id is null
       and valid_from <= ${params.workDate}::date
       and (valid_to is null or valid_to >= ${params.workDate}::date)
  `);
  return result.rows.map((row) => ({
    id: row.id,
    tierFrom: row.tier_from,
    tierTo: row.tier_to,
    ratePerUnit: row.rate_per_unit,
    minDaily: row.min_daily,
  }));
}

/** the matched rule's full row (brief: "rule_snapshot is populated" with "the matched rule's full
 *  row"). */
async function getCommissionRuleSnapshot(tx: NodePgDatabase, ruleId: string): Promise<Record<string, unknown>> {
  const result = await tx.execute<Record<string, unknown>>(sql`
    select id, entity_id, name, applies_to, client_id, tier_from, tier_to,
           rate_per_unit::text as rate_per_unit, min_daily::text as min_daily, valid_from, valid_to
      from ${sql.raw(COMMISSION_RULES_TABLE)}
     where id = ${ruleId}::uuid
  `);
  const row = result.rows[0];
  if (!row) throw new Error(`no ${COMMISSION_RULES_TABLE} row for id ${ruleId} (matched moments earlier)`);
  return row;
}

/** INSERT into hr.commission_daily, status always 'calculated' this slice (brief, Deliver). `id`
 *  is pre-generated by the application layer — no RETURNING clause (see this file's own header).
 *  `version` stays its column default (1, migration 0027) — no column list entry needed. Translates
 *  the DB's own `commission_daily_work_date_employee_id_key` unique violation to
 *  `CommissionAlreadyCalculatedError`. */
async function insertCommissionDaily(tx: NodePgDatabase, columns: InsertCommissionDailyColumns): Promise<void> {
  try {
    await tx.execute(sql`
      insert into ${sql.raw(COMMISSION_DAILY_TABLE)}
        (id, entity_id, work_date, employee_id, driver_id_ref, delivered_count, failed_count,
         returned_count, gross_commission, source_snapshot, rule_snapshot, status)
      values
        (${columns.id}::uuid, ${columns.entityId}::uuid, ${columns.workDate}::date,
         ${columns.employeeId}::uuid, ${columns.driverIdRef}::uuid, ${columns.deliveredCount}::int,
         ${columns.failedCount}::int, ${columns.returnedCount}::int,
         ${columns.grossCommission}::numeric, ${JSON.stringify(columns.sourceSnapshot)}::jsonb,
         ${JSON.stringify(columns.ruleSnapshot)}::jsonb, ${COMMISSION_DAILY_STATUS_CALCULATED})
    `);
  } catch (error) {
    if (isDuplicateCommissionDaily(error)) {
      throw new CommissionAlreadyCalculatedError(
        `a ${COMMISSION_DAILY_TABLE} row for employee ${columns.employeeId} and work_date ` +
          `${columns.workDate} already exists (${COMMISSION_DAILY_UNIQUE_CONSTRAINT}). Allowed: one ` +
          `calculation per employee per day.`,
        { cause: error },
      );
    }
    throw error;
  }
}

/** doc 40 P3/P7: one append-only platform.audit_log row per write this use case performs — same
 *  hash-chain mechanism (a DB trigger, not application code) every prior slice already writes
 *  through its own `writeAuditRow`. No RETURNING here either (this insert was never affected by the
 *  RLS-on-RETURNING gap this file's header describes — platform.audit_log carries its own,
 *  unrelated write policy every prior slice already relies on). */
async function writeAuditRow(
  tx: NodePgDatabase,
  params: {
    readonly entityId: string;
    readonly recordId: string;
    readonly operation: string;
    readonly correlationId: string;
    readonly actorId: string;
    readonly newValue: unknown;
    readonly occurredAt: Date;
  },
): Promise<void> {
  await tx.execute(sql`
    insert into platform.audit_log
      (occurred_at, user_id, actor_type, entity_id, schema_name, table_name, record_id, operation,
       new_value, correlation_id)
    values
      (${params.occurredAt.toISOString()}::timestamptz, ${params.actorId}::uuid, ${AUDIT_ACTOR_TYPE_USER},
       ${params.entityId}::uuid, ${COMMISSION_SCHEMA}, ${COMMISSION_DAILY_TABLE_NAME}, ${params.recordId}::uuid,
       ${params.operation}, ${JSON.stringify(params.newValue)}::jsonb, ${params.correlationId}::uuid)
  `);
}

export const commissionDailyRepository: CommissionDailyRepository = {
  resolveCallerEntityId,
  getEmployeeEntityId,
  getAttributedShipmentCounts,
  getActiveDriverIdRef,
  getCandidateCommissionRules,
  getCommissionRuleSnapshot,
  insertCommissionDaily,
  writeAuditRow,
};

// REPLACE-ON-COPY: the module-schema-qualified constants a later slice's copy must change.
export { COMMISSION_SCHEMA, COMMISSION_DAILY_TABLE_NAME, COMMISSION_DAILY_TABLE, COMMISSION_RULES_TABLE };
